// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtN_3wOlxILrXJMFksloCWltunk_T01y0',
    appId: '1:22525020677:web:6f88955efec427030f2a6c',
    messagingSenderId: '22525020677',
    projectId: 'hostel-70c69',
    authDomain: 'hostel-70c69.firebaseapp.com',
    storageBucket: 'hostel-70c69.appspot.com',
    measurementId: 'G-5HF3XPPVYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJr_vw9bKS-0z492fFLBta_a8Fl8dxtVQ',
    appId: '1:22525020677:android:b9176f52d3a2ec820f2a6c',
    messagingSenderId: '22525020677',
    projectId: 'hostel-70c69',
    storageBucket: 'hostel-70c69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQj3Cvg9fiHJlOJD7K7168wq-KcVa_Iq4',
    appId: '1:22525020677:ios:8017a6a2edd3bec90f2a6c',
    messagingSenderId: '22525020677',
    projectId: 'hostel-70c69',
    storageBucket: 'hostel-70c69.appspot.com',
    iosBundleId: 'com.example.piethostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQj3Cvg9fiHJlOJD7K7168wq-KcVa_Iq4',
    appId: '1:22525020677:ios:8017a6a2edd3bec90f2a6c',
    messagingSenderId: '22525020677',
    projectId: 'hostel-70c69',
    storageBucket: 'hostel-70c69.appspot.com',
    iosBundleId: 'com.example.piethostel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtN_3wOlxILrXJMFksloCWltunk_T01y0',
    appId: '1:22525020677:web:2fb4727ca22888b20f2a6c',
    messagingSenderId: '22525020677',
    projectId: 'hostel-70c69',
    authDomain: 'hostel-70c69.firebaseapp.com',
    storageBucket: 'hostel-70c69.appspot.com',
    measurementId: 'G-WHK55P30FZ',
  );
}
